package biz.belcorp.salesforce.core.events


enum class EventSubject {

    HOME_SYNC,
    CORE_SYNC,
    DIGITAL_SYNC,
    CAMPAIGNS_SYNC,
    CONSULTANTS_SYNC,
    CONSULTANTS_LOCATION,
    VIRTUAL_METHODOLOGY_SYNC,
    DEVELOPMENT_MATERIAL_SYNC,
    DEVELOPMENT_PATH_LEGACY_SYNC,
    DEVELOPMENT_PATH_DASHBOARD_SYNC,
    CALCULATOR_SYNC,
    POSTULANTS_SYNC,
    POSTULANTS_APPLICATIONS_SYNC,
    KPIS_COLLECTION_SYNC,
    KPIS_KPIS_SYNC,
    BRIGHT_PATH_SYNC,
    MESSAGING_SYNC,
    POLITICS_TERMS_CONDITIONS_SYNC,
    INSPIRES_SYNC,

    CONSULTANT_FILTERS,
    COLLECTION_31_DAYS,
    LOGOUT,
    SHARE_LINK_SE,
    TERM_COOKIES

}
