package biz.belcorp.salesforce.modules.postulants.core.domain.enums

enum class UneteTipoParametro(val tipo: Int) {
    LUGARNIVEL1(5),
    LUGARNIVEL3(7),
    ZONASMS(14),
    MOTIVORECHAZOSE(18),
    TIPODOCUMENTO(20),
    NIVELRIESGO(22),
    SUFIJOS_DOCS_BOLIVIA(30),
    REGIMENCONTABLE(35),
    ZONA(34),
    RANGOZONA(35),
    RANGOEDAD(43),
    REVISIONDOCUMENTOSAC(46),
    MAPARADIO(53),
    OPCIONESPAGOCONTADO(56),
    ZONAPAGOCONTADO(57),
    SECCIONESCRITICAS(71),
    CORREOOBLIGATORIO(72),
    RECHAZOPROACTIVAS(73),
    AUTOCOMPLETADO_DIRECCION(77),
    LOCATION_MAP_BY_ADRESS(78)
}
