package biz.belcorp.salesforce.core.constants

const val FUNCTION_SALE_ORDERS_NAME_KEY = "Kpi_sale_order"
const val FILTER_SALE_ORDERS_KEY = "paramsSales"
const val FILTER_SALE_ORDERS_TYPE_KEY = "ParamsSales"
const val COLLECTION_SALE_ORDERS_KEY = "KpiSalesOrdersV2"
const val INPUT_SALE_ORDERS_KEY = "input"

const val KEY_REAL = "real"
const val KEY_ORDERS = "orders"
const val KEY_SALES = "sales"
const val KEY_NET_SALE_REAL = "net_sale_real"
const val KEY_NET_SALE_GOAL = "net_sale_goal"
const val KEY_FULFILLMENT_NET_SALES_PERCENTAGE = "fulfillment_net_sales_percentage"
const val KEY_ACTIVES = "actives"
const val KEY_FINALS = "finals"
const val KEY_FINALS_LAST_YEAR = "finals_lastyear"
const val KEY_MULTIBRAND = "multibrand"
const val KEY_MULTIBRAND_PERCENTAGE = "percentage"
const val KEY_MULTIBRAND_ACTIVES = "actives"
const val KEY_MULTIBRAND_NO_MULTIBRAND_ACTIVES = "no_multibrand_actives"
const val KEY_MULTIBRAND_LASTCAMPAIGN = "lastcampaign"
const val KEY_MULTIBRAND_VS_LASTCAMPAIGN = "vs_lastcampaign"
const val KEY_MULTIBRAND_NUM_VS_LASTCAMPAIGN = "num_vs_lastcampaign"
const val KEY_MULTIBRAND_ACTIVES_HIGH_VALUE = "actives_high_value"
const val KEY_MULTIBRAND_ORDERS_HIGH_VALUE = "orders_high_value"
const val KEY_MULTIBRAND_HIGH_VALUE_NUM_VS_LAST_CAMPAIGN = "high_value_num_vs_lastcampaign"
