name: ci-cd-wf-sales-force-mobile-android
on:  
  push:
    branches: [master, review , release/*, develop]
  pull_request:
    branches: [master, review , release/*, develop]

jobs:
  ci-cd-wf-sales-force-mobile-android:
    uses: tech-belcorp/devops-framework/.github/workflows/wf-android-fastlane.yml@1.3.3
    with:
      runs-on: 'devops-runner-large-8-32'
      path-build-bundle: "app/build/outputs/bundle"
      path-build-mapping: "app/build/outputs/mapping"
      project-name: "AppFFVV"
      services: '["businesspartners", "multiprofile"]'
      flag-download-config: true
      path-applications: "SalesForceMobile"
      branching-model: 'gitflow-ffvv-android'
      flag-sales-force-mobile-android: true
      flag-deploy-fastlane-enabled: true
    secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        PAT_PACKAGES_RO: ${{ secrets.PAT_PACKAGES_RO }}
        IAM_ARN: ${{ secrets.AWS_ARN_ROLE_GITHUB }}

